spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/teamratings
    username: z002ldj
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO

server:
  port: 8080
  sessionTimeout: 30